services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"  # 将宿主机的 80 端口映射到容器的 80 端口
    networks:
      - webnet
    restart: always 

networks:
  webnet:
    driver: bridge
